---
- hosts: all
  become: true
  tasks:
  - name: install maven
    apt:
      pkg: maven
      state: present
    notify:
    - run update
  - name: install tomcat
    apt:
      pkg: tomcat9
      state: present
  - name: uninstall git
    apt:
      pkg: git
      state: absent
  - name: install docker
    apt:
      pkg: docker.io
      state: present
  - name: start docker service
    service:
      name: docker
      state: started
      enabled: true
  
  - name: Stop container if application is already running
    command: docker stop casestudy
    ignore_errors: yes
    
  - name: Remove container if exists
    command: docker rm casestudy
    ignore_errors: yes
    
  - name: Deploy application
    command: docker run -it -d -p 8081:8888 --name casestudy ailamadu/casestudy:1.0
  
  handlers:
  - name: run update
    apt:
      update_cache: yes
